openapi: 3.0.0
info:
  title: 'Your API Title'
  version: '1.0.0'
  description: 'Your API Description'
tags:
  - name: Logs
    description: API endpoints for managing logs
  - name: Health
    description: API endpoint for health check
paths:
  /log:
    post:
      summary: Create a new log
      tags: [Logs]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: 'object'
              properties:
                message:
                  type: 'string'
              required:
                - 'message'
      responses:
        '201':
          description: Created
          content:
            application/json:
              example:
                logMessage: { message: 'Log created successfully' }
        '400':
          description: Bad Request
          content:
            application/json:
              example:
                message: Validation error
                errors: ['message is required']
  /health:
    get:
      summary: Health Check
      tags: [Health]
      responses:
        '200':
          description: OK
          content:
            text/plain:
              example: 'OK!'
